In [1]:
import numpy as np

In [2]:
x=np.array([1,7,9,8])

In [3]:
x[x>2]

array([7, 9, 8])

In [5]:
x[[2,1]]

array([9, 7])

In [8]:
x=np.random.randn(10,10)

In [9]:
x[0][4]

0.6104401209348738

In [10]:
x=np.ones((5,5))

In [11]:
x[1:-1,1:-1]=0

In [12]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Functions

In [13]:
x=np.array([7,8,9,12])

In [14]:
np.sqrt(x)

array([2.64575131, 2.82842712, 3.        , 3.46410162])

In [15]:
np.power(x,2)

array([ 49,  64,  81, 144], dtype=int32)

In [18]:
y=np.array([3,4,14,9])

In [19]:
np.maximum(x,y)

array([ 7,  8, 14, 12])