In [1]:
import numpy as np

In [5]:
salary=np.array([0,-1,100000,50000])

In [6]:
np.where(salary<=0,25000,salary)

array([ 25000,  25000, 100000,  50000])

In [7]:
np.where(salary<=0,"Not OK","OK")

array(['Not OK', 'Not OK', 'OK', 'OK'], dtype='<U6')

# Statistics

In [9]:
import numpy as np

In [10]:
x=np.array([10,9,7,8,10,7])

In [12]:
x.mean()

8.5

In [13]:
x.cumsum()

array([10, 19, 26, 34, 44, 51], dtype=int32)

In [15]:
x.cumprod()

array([    10,     90,    630,   5040,  50400, 352800], dtype=int32)

In [16]:
y=x>6

In [17]:
y

array([ True,  True,  True,  True,  True,  True])

In [18]:
y.sum()

6

In [19]:
y.any()

True

In [20]:
y.all()

True

In [21]:
y=x>7

In [22]:
y

array([ True,  True, False,  True,  True, False])

In [23]:
y.sum()

4

In [24]:
y.all()

False

In [25]:
y.any()

True

In [26]:
x.sort()

In [27]:
x

array([ 7,  7,  8,  9, 10, 10])

In [29]:
np.unique(x)

array([ 7,  8,  9, 10])